version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
workflows:
  deploy-teamsocial-quiz-app:
    jobs:
      - test 
      - heroku/deploy-via-git:          
          filters:
            branches:
              only: main
   
jobs:
  test:
    docker:
      - image: cimg/node:14.17.3
    steps:
      - checkout
      - run:
          name: install dependiceies
          command: npm install
      - run:
          name: tests
          command: npm run test
  build:
    docker:
      - image: cimg/node:14.13.0
    
    steps:
      - checkout
      - run:
          name: install dependiceies
          command: npm install
 
